from building import *
import BuildLists as bl

cwd = GetCurrentDir()

src = []
for f in bl.TASKS:
    src += Glob(f)

if GetDepend(['RT_USING_CPLUSPLUS']):
    src += Glob('*.cpp')

inc = []
for d in bl.TASKS_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('Task', src, depend=[''], CPPPATH=inc)

Return('group')

